### PR TITLE
 Portuguese translation..

### PR DESCRIPTION
**Pull request by gustavovitor**
Tomirons, very thanks for this code, you're very gentle..

I'm having problems in the ranking system, outside this, everything works perfectly!

..if you want, take this merge with portuguese translation for your code!

### CODE REVIEW

**Comment by gustavovitor** [comment]
Ranking is now working! (crontabs suck's) haha..
Thanks, @tomirons

**Review by BahaStriker — APPROVED** [review]

**Comment by HyperSin** [comment]
how did you fix the ranking?

**Comment by gustavovitor** [comment]
Easy, but my case is be different.. For me, i have debugged the schedule commands, specifically the factions code, and watch in my server API, i made changes in the hex code positions functions for this case.

But you can make one factions ranking system more easy using SQL Triggers, before update in players ranking table.

**Comment by HyperSin** [comment]
Im glad you fixed it, players appears to be working, factions still dont work, i dont think the panel is sending factions to database cause its empty, also where  do i add the new class names and icons at, i got the bm icon and class11 and i also wanna add deaths how many times they died, etc, I found  a ranking system on knife but when i added the new classes the website stopped working and when i started it it used up all the ram in my system cause it wouldn't let me do anything, (cannot allocate memory) , the system is a 256gig ram system so i cant use that ranking system

**Comment by HyperSin** [comment]
I take it back, player dont work ither, and its not worth fixing,

**Pull request merged**
